# Actions train a model on Azure Machine Learning
name: aml-train-deploy-workflow 
on: [push, pull_request]
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
        
    # Connect or Create the Azure Machine Learning Workspace
    - name: Connect/Create Azure Machine Learning Workspace
      id: aml_workspace
      uses: Azure/aml-workspace@azuremlsdk_1_5_0
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Register model in Azure Machine Learning model registry
    - name: Register model
      id: aml_registermodel
      uses: Azure/aml-registermodel@azuremlsdk_1_5_0
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          parameters_file: "registermodel2.json"
